//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto copies all properties into another AegisPolicy.
func (in *AegisPolicy) DeepCopyInto(out *AegisPolicy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy returns a deep copy of AegisPolicy.
func (in *AegisPolicy) DeepCopy() *AegisPolicy {
	if in == nil {
		return nil
	}
	out := new(AegisPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject implements runtime.Object.
func (in *AegisPolicy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto copies all properties into another AegisPolicyList.
func (in *AegisPolicyList) DeepCopyInto(out *AegisPolicyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AegisPolicy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy returns a deep copy of AegisPolicyList.
func (in *AegisPolicyList) DeepCopy() *AegisPolicyList {
	if in == nil {
		return nil
	}
	out := new(AegisPolicyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject implements runtime.Object.
func (in *AegisPolicyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto copies all properties into another AegisClusterPolicy.
func (in *AegisClusterPolicy) DeepCopyInto(out *AegisClusterPolicy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy returns a deep copy of AegisClusterPolicy.
func (in *AegisClusterPolicy) DeepCopy() *AegisClusterPolicy {
	if in == nil {
		return nil
	}
	out := new(AegisClusterPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject implements runtime.Object.
func (in *AegisClusterPolicy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto copies all properties into another AegisClusterPolicyList.
func (in *AegisClusterPolicyList) DeepCopyInto(out *AegisClusterPolicyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AegisClusterPolicy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy returns a deep copy of AegisClusterPolicyList.
func (in *AegisClusterPolicyList) DeepCopy() *AegisClusterPolicyList {
	if in == nil {
		return nil
	}
	out := new(AegisClusterPolicyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject implements runtime.Object.
func (in *AegisClusterPolicyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto copies AegisPolicySpec.
func (in *AegisPolicySpec) DeepCopyInto(out *AegisPolicySpec) {
	*out = *in
	if in.Selector != nil {
		in, out := &in.Selector, &out.Selector
		*out = new(PolicySelector)
		(*in).DeepCopyInto(*out)
	}
	if in.FileRules != nil {
		in, out := &in.FileRules, &out.FileRules
		*out = new(FileRules)
		(*in).DeepCopyInto(*out)
	}
	if in.NetworkRules != nil {
		in, out := &in.NetworkRules, &out.NetworkRules
		*out = new(NetworkRules)
		(*in).DeepCopyInto(*out)
	}
	if in.ExecRules != nil {
		in, out := &in.ExecRules, &out.ExecRules
		*out = new(ExecRules)
		(*in).DeepCopyInto(*out)
	}
	if in.KernelRules != nil {
		in, out := &in.KernelRules, &out.KernelRules
		*out = new(KernelRules)
		**out = **in
	}
}

// DeepCopy returns a deep copy of AegisPolicySpec.
func (in *AegisPolicySpec) DeepCopy() *AegisPolicySpec {
	if in == nil {
		return nil
	}
	out := new(AegisPolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies PolicySelector.
func (in *PolicySelector) DeepCopyInto(out *PolicySelector) {
	*out = *in
	if in.MatchLabels != nil {
		in, out := &in.MatchLabels, &out.MatchLabels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.MatchNamespaces != nil {
		in, out := &in.MatchNamespaces, &out.MatchNamespaces
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy returns a deep copy of PolicySelector.
func (in *PolicySelector) DeepCopy() *PolicySelector {
	if in == nil {
		return nil
	}
	out := new(PolicySelector)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies FileRules.
func (in *FileRules) DeepCopyInto(out *FileRules) {
	*out = *in
	if in.Deny != nil {
		in, out := &in.Deny, &out.Deny
		*out = make([]FileRule, len(*in))
		copy(*out, *in)
	}
	if in.Protect != nil {
		in, out := &in.Protect, &out.Protect
		*out = make([]FileRule, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy returns a deep copy of FileRules.
func (in *FileRules) DeepCopy() *FileRules {
	if in == nil {
		return nil
	}
	out := new(FileRules)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies NetworkRules.
func (in *NetworkRules) DeepCopyInto(out *NetworkRules) {
	*out = *in
	if in.Deny != nil {
		in, out := &in.Deny, &out.Deny
		*out = make([]NetworkRule, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy returns a deep copy of NetworkRules.
func (in *NetworkRules) DeepCopy() *NetworkRules {
	if in == nil {
		return nil
	}
	out := new(NetworkRules)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies ExecRules.
func (in *ExecRules) DeepCopyInto(out *ExecRules) {
	*out = *in
	if in.AllowBinaryHashes != nil {
		in, out := &in.AllowBinaryHashes, &out.AllowBinaryHashes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.DenyBinaryHashes != nil {
		in, out := &in.DenyBinaryHashes, &out.DenyBinaryHashes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.DenyComm != nil {
		in, out := &in.DenyComm, &out.DenyComm
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy returns a deep copy of ExecRules.
func (in *ExecRules) DeepCopy() *ExecRules {
	if in == nil {
		return nil
	}
	out := new(ExecRules)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies KernelRules.
func (in *KernelRules) DeepCopyInto(out *KernelRules) {
	*out = *in
}

// DeepCopy returns a deep copy of KernelRules.
func (in *KernelRules) DeepCopy() *KernelRules {
	if in == nil {
		return nil
	}
	out := new(KernelRules)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies AegisPolicyStatus.
func (in *AegisPolicyStatus) DeepCopyInto(out *AegisPolicyStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.LastAppliedAt != nil {
		in, out := &in.LastAppliedAt, &out.LastAppliedAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy returns a deep copy of AegisPolicyStatus.
func (in *AegisPolicyStatus) DeepCopy() *AegisPolicyStatus {
	if in == nil {
		return nil
	}
	out := new(AegisPolicyStatus)
	in.DeepCopyInto(out)
	return out
}
