// Package policy translates AegisPolicy CRD specs into the Aegis INI policy
// format consumed by the C++ daemon.
package policy

import (
	"crypto/sha256"
	"fmt"
	"sort"
	"strings"

	v1alpha1 "github.com/ErenAri/aegis-operator/api/v1alpha1"
)

// TranslateResult holds the generated INI policy and its content hash.
type TranslateResult struct {
	INI    string
	SHA256 string
}

// TranslateToINI converts an AegisPolicySpec into the Aegis INI policy format.
// The INI format is consumed by the C++ daemon's policy_parse.cpp.
func TranslateToINI(spec v1alpha1.AegisPolicySpec) (TranslateResult, error) {
	var b strings.Builder

	b.WriteString("version=5\n")
	b.WriteString(fmt.Sprintf("# mode=%s\n", spec.Mode))
	b.WriteString("# Generated by aegis-operator from AegisPolicy CRD\n\n")

	if spec.FileRules != nil {
		if len(spec.FileRules.Deny) > 0 {
			var paths, inodes []string
			for _, rule := range spec.FileRules.Deny {
				if rule.Path != "" {
					paths = append(paths, rule.Path)
				}
				if rule.Inode != "" {
					inodes = append(inodes, rule.Inode)
				}
			}
			if len(paths) > 0 {
				b.WriteString("[deny_path]\n")
				for _, p := range paths {
					b.WriteString(p + "\n")
				}
				b.WriteString("\n")
			}
			if len(inodes) > 0 {
				b.WriteString("[deny_inode]\n")
				for _, i := range inodes {
					b.WriteString(i + "\n")
				}
				b.WriteString("\n")
			}
		}

		if len(spec.FileRules.Protect) > 0 {
			b.WriteString("[protect_path]\n")
			for _, rule := range spec.FileRules.Protect {
				if rule.Path != "" {
					b.WriteString(rule.Path + "\n")
				}
			}
			b.WriteString("\n")
		}
	}

	if spec.NetworkRules != nil && len(spec.NetworkRules.Deny) > 0 {
		var ips, cidrs, ports, ipPorts []string
		for _, rule := range spec.NetworkRules.Deny {
			switch {
			case rule.IP != "" && rule.Port > 0:
				proto := rule.Protocol
				if proto == "" {
					proto = "tcp"
				}
				dir := rule.Direction
				if dir == "" {
					dir = "outbound"
				}
				ipPorts = append(ipPorts, fmt.Sprintf("%s:%s:%d:%s", rule.IP, proto, rule.Port, dir))
			case rule.IP != "":
				ips = append(ips, rule.IP)
			case rule.CIDR != "":
				cidrs = append(cidrs, rule.CIDR)
			case rule.Port > 0:
				proto := rule.Protocol
				if proto == "" {
					proto = "tcp"
				}
				dir := rule.Direction
				if dir == "" {
					dir = "outbound"
				}
				ports = append(ports, fmt.Sprintf("%s:%d:%s", proto, rule.Port, dir))
			}
		}

		if len(ips) > 0 {
			b.WriteString("[deny_ip]\n")
			for _, ip := range ips {
				b.WriteString(ip + "\n")
			}
			b.WriteString("\n")
		}
		if len(cidrs) > 0 {
			b.WriteString("[deny_cidr]\n")
			for _, cidr := range cidrs {
				b.WriteString(cidr + "\n")
			}
			b.WriteString("\n")
		}
		if len(ports) > 0 {
			b.WriteString("[deny_port]\n")
			for _, port := range ports {
				b.WriteString(port + "\n")
			}
			b.WriteString("\n")
		}
		if len(ipPorts) > 0 {
			b.WriteString("[deny_ip_port]\n")
			for _, ipp := range ipPorts {
				b.WriteString(ipp + "\n")
			}
			b.WriteString("\n")
		}
	}

	if spec.ExecRules != nil {
		if len(spec.ExecRules.AllowBinaryHashes) > 0 {
			b.WriteString("[allow_binary_hash]\n")
			for _, h := range spec.ExecRules.AllowBinaryHashes {
				b.WriteString("sha256:" + h + "\n")
			}
			b.WriteString("\n")
		}
		if len(spec.ExecRules.DenyBinaryHashes) > 0 {
			b.WriteString("[deny_binary_hash]\n")
			for _, h := range spec.ExecRules.DenyBinaryHashes {
				b.WriteString("sha256:" + h + "\n")
			}
			b.WriteString("\n")
		}
	}

	if spec.KernelRules != nil {
		if spec.KernelRules.BlockPtrace {
			b.WriteString("[deny_ptrace]\n*\n\n")
		}
		if spec.KernelRules.BlockModuleLoad {
			b.WriteString("[deny_module_load]\n*\n\n")
		}
		if spec.KernelRules.BlockBpfSyscall {
			b.WriteString("[deny_bpf]\n*\n\n")
		}
	}

	content := b.String()
	hash := fmt.Sprintf("%x", sha256.Sum256([]byte(content)))

	return TranslateResult{
		INI:    content,
		SHA256: hash,
	}, nil
}

// MergePolicies combines multiple translated policies into a single INI.
// Later policies override earlier ones for conflicting rules.
func MergePolicies(policies []TranslateResult) TranslateResult {
	var combined strings.Builder
	combined.WriteString("version=5\n")
	combined.WriteString("# Merged policy generated by aegis-operator\n\n")

	sections := make(map[string][]string)
	for _, p := range policies {
		currentSection := ""
		for _, line := range strings.Split(p.INI, "\n") {
			line = strings.TrimSpace(line)
			if line == "" || strings.HasPrefix(line, "#") || strings.HasPrefix(line, "version=") {
				continue
			}
			if strings.HasPrefix(line, "[") && strings.HasSuffix(line, "]") {
				currentSection = line
				continue
			}
			if currentSection != "" {
				sections[currentSection] = appendUnique(sections[currentSection], line)
			}
		}
	}

	sortedSections := make([]string, 0, len(sections))
	for section := range sections {
		sortedSections = append(sortedSections, section)
	}
	sort.Strings(sortedSections)

	for _, section := range sortedSections {
		entries := sections[section]
		combined.WriteString(section + "\n")
		for _, entry := range entries {
			combined.WriteString(entry + "\n")
		}
		combined.WriteString("\n")
	}

	content := combined.String()
	hash := fmt.Sprintf("%x", sha256.Sum256([]byte(content)))
	return TranslateResult{INI: content, SHA256: hash}
}

func appendUnique(slice []string, item string) []string {
	for _, s := range slice {
		if s == item {
			return slice
		}
	}
	return append(slice, item)
}
