// Package policy translates AegisPolicy CRD specs into the Aegis INI policy
// format consumed by the C++ daemon.
package policy

import (
	"crypto/sha256"
	"fmt"
	"sort"
	"strings"

	v1alpha1 "github.com/ErenAri/aegis-operator/api/v1alpha1"
)

// TranslateResult holds the generated INI policy and its content hash.
type TranslateResult struct {
	INI    string
	SHA256 string
}

// allowOverrideMap maps an Allow section name to its corresponding Deny
// section. Within a merged cluster policy, any literal that appears in an
// allow_* section is removed from the corresponding deny_* section, so
// Allow takes precedence over Block. This mirrors Tetragon and KubeArmor
// behaviour and is documented in docs/POLICY_SEMANTICS.md.
var allowOverrideMap = map[string]string{
	"[allow_path]":        "[deny_path]",
	"[allow_ip]":          "[deny_ip]",
	"[allow_cidr]":        "[deny_cidr]",
	"[allow_port]":        "[deny_port]",
	"[allow_ip_port]":     "[deny_ip_port]",
	"[allow_binary_hash]": "[deny_binary_hash]",
}

// TranslateToINI converts an AegisPolicySpec into the Aegis INI policy format.
// The INI format is consumed by the C++ daemon's policy_parse.cpp.
//
// Per-rule Action (Allow/Block, default Block) controls which INI section
// each rule lands in: Block rules go into `[deny_*]` sections, Allow rules
// go into `[allow_*]` sections. The daemon already understands both halves;
// no daemon change is required to support per-rule actions.
func TranslateToINI(spec v1alpha1.AegisPolicySpec) (TranslateResult, error) {
	var b strings.Builder

	b.WriteString("version=5\n")
	b.WriteString(fmt.Sprintf("# mode=%s\n", spec.Mode))
	b.WriteString("# Generated by aegis-operator from AegisPolicy CRD\n\n")

	buildFileSections(&b, spec.FileRules)
	buildNetworkSections(&b, spec.NetworkRules)
	buildExecSections(&b, spec.ExecRules)
	buildKernelSections(&b, spec.KernelRules)

	content := b.String()
	hash := fmt.Sprintf("%x", sha256.Sum256([]byte(content)))
	return TranslateResult{INI: content, SHA256: hash}, nil
}

// emitSection writes a non-empty `[name]\nentry\n...` block, sorting and
// de-duplicating entries so the output is deterministic across reconciles.
func emitSection(b *strings.Builder, name string, entries []string) {
	if len(entries) == 0 {
		return
	}
	seen := make(map[string]struct{}, len(entries))
	deduped := make([]string, 0, len(entries))
	for _, e := range entries {
		if _, ok := seen[e]; ok {
			continue
		}
		seen[e] = struct{}{}
		deduped = append(deduped, e)
	}
	sort.Strings(deduped)
	b.WriteString("[" + name + "]\n")
	for _, e := range deduped {
		b.WriteString(e + "\n")
	}
	b.WriteString("\n")
}

// isAllow reports whether a rule action is Allow. An empty action defaults
// to Block, so we only check for the explicit Allow value.
func isAllow(a v1alpha1.RuleAction) bool { return a == v1alpha1.RuleActionAllow }

func buildFileSections(b *strings.Builder, fr *v1alpha1.FileRules) {
	if fr == nil {
		return
	}

	var denyPaths, allowPaths, denyInodes []string
	for _, r := range fr.Deny {
		if isAllow(r.Action) {
			// Inode-based Allow is not a daemon concept; webhook rejects
			// the combination, but defensively skip it here too.
			if r.Path != "" {
				allowPaths = append(allowPaths, r.Path)
			}
			continue
		}
		if r.Path != "" {
			denyPaths = append(denyPaths, r.Path)
		}
		if r.Inode != "" {
			denyInodes = append(denyInodes, r.Inode)
		}
	}

	var protectPaths []string
	for _, r := range fr.Protect {
		if r.Path != "" {
			protectPaths = append(protectPaths, r.Path)
		}
	}

	emitSection(b, "deny_path", denyPaths)
	emitSection(b, "allow_path", allowPaths)
	emitSection(b, "deny_inode", denyInodes)
	emitSection(b, "protect_path", protectPaths)
}

func buildNetworkSections(b *strings.Builder, nr *v1alpha1.NetworkRules) {
	if nr == nil || len(nr.Deny) == 0 {
		return
	}

	var (
		denyIPs, denyCIDRs, denyPorts, denyIPPorts         []string
		allowIPs, allowCIDRs, allowPorts, allowIPPorts     []string
	)

	collect := func(rule v1alpha1.NetworkRule, ips, cidrs, ports, ipPorts *[]string) {
		switch {
		case rule.IP != "" && rule.Port > 0:
			proto := rule.Protocol
			if proto == "" {
				proto = "tcp"
			}
			dir := rule.Direction
			if dir == "" {
				dir = "outbound"
			}
			*ipPorts = append(*ipPorts, fmt.Sprintf("%s:%s:%d:%s", rule.IP, proto, rule.Port, dir))
		case rule.IP != "":
			*ips = append(*ips, rule.IP)
		case rule.CIDR != "":
			*cidrs = append(*cidrs, rule.CIDR)
		case rule.Port > 0:
			proto := rule.Protocol
			if proto == "" {
				proto = "tcp"
			}
			dir := rule.Direction
			if dir == "" {
				dir = "outbound"
			}
			*ports = append(*ports, fmt.Sprintf("%s:%d:%s", proto, rule.Port, dir))
		}
	}

	for _, r := range nr.Deny {
		if isAllow(r.Action) {
			collect(r, &allowIPs, &allowCIDRs, &allowPorts, &allowIPPorts)
		} else {
			collect(r, &denyIPs, &denyCIDRs, &denyPorts, &denyIPPorts)
		}
	}

	emitSection(b, "deny_ip", denyIPs)
	emitSection(b, "allow_ip", allowIPs)
	emitSection(b, "deny_cidr", denyCIDRs)
	emitSection(b, "allow_cidr", allowCIDRs)
	emitSection(b, "deny_port", denyPorts)
	emitSection(b, "allow_port", allowPorts)
	emitSection(b, "deny_ip_port", denyIPPorts)
	emitSection(b, "allow_ip_port", allowIPPorts)
}

func buildExecSections(b *strings.Builder, er *v1alpha1.ExecRules) {
	if er == nil {
		return
	}
	if len(er.AllowBinaryHashes) > 0 {
		entries := make([]string, 0, len(er.AllowBinaryHashes))
		for _, h := range er.AllowBinaryHashes {
			entries = append(entries, "sha256:"+h)
		}
		emitSection(b, "allow_binary_hash", entries)
	}
	if len(er.DenyBinaryHashes) > 0 {
		entries := make([]string, 0, len(er.DenyBinaryHashes))
		for _, h := range er.DenyBinaryHashes {
			entries = append(entries, "sha256:"+h)
		}
		emitSection(b, "deny_binary_hash", entries)
	}
}

func buildKernelSections(b *strings.Builder, kr *v1alpha1.KernelRules) {
	if kr == nil {
		return
	}
	if kr.BlockPtrace {
		emitSection(b, "deny_ptrace", []string{"*"})
	}
	if kr.BlockModuleLoad {
		emitSection(b, "deny_module_load", []string{"*"})
	}
	if kr.BlockBpfSyscall {
		emitSection(b, "deny_bpf", []string{"*"})
	}
}

// MergePolicies combines multiple translated policies into a single INI.
// Sections are unioned and entries within each section are de-duplicated.
//
// Allow > Block precedence: any literal that appears in an `[allow_*]`
// section is removed from the matching `[deny_*]` section. This is the
// same conflict-resolution rule used by Tetragon and KubeArmor and is
// documented in docs/POLICY_SEMANTICS.md.
func MergePolicies(policies []TranslateResult) TranslateResult {
	sections := make(map[string][]string)
	for _, p := range policies {
		currentSection := ""
		for _, line := range strings.Split(p.INI, "\n") {
			line = strings.TrimSpace(line)
			if line == "" || strings.HasPrefix(line, "#") || strings.HasPrefix(line, "version=") {
				continue
			}
			if strings.HasPrefix(line, "[") && strings.HasSuffix(line, "]") {
				currentSection = line
				continue
			}
			if currentSection != "" {
				sections[currentSection] = appendUnique(sections[currentSection], line)
			}
		}
	}

	// Apply Allow > Block precedence: remove any deny entry whose literal
	// also appears in the corresponding allow section.
	for allowSection, denySection := range allowOverrideMap {
		allowed := sections[allowSection]
		if len(allowed) == 0 {
			continue
		}
		denied := sections[denySection]
		if len(denied) == 0 {
			continue
		}
		allowedSet := make(map[string]struct{}, len(allowed))
		for _, e := range allowed {
			allowedSet[e] = struct{}{}
		}
		kept := make([]string, 0, len(denied))
		for _, e := range denied {
			if _, blocked := allowedSet[e]; blocked {
				continue
			}
			kept = append(kept, e)
		}
		sections[denySection] = kept
	}

	// Sort section names and entries within each section so the merged
	// INI is byte-stable across reconciles.
	sortedSections := make([]string, 0, len(sections))
	for section := range sections {
		sortedSections = append(sortedSections, section)
	}
	sort.Strings(sortedSections)

	var combined strings.Builder
	combined.WriteString("version=5\n")
	combined.WriteString("# Merged policy generated by aegis-operator\n\n")

	for _, section := range sortedSections {
		entries := sections[section]
		if len(entries) == 0 {
			// Section was emptied by the Allow override sweep — drop it.
			continue
		}
		sort.Strings(entries)
		combined.WriteString(section + "\n")
		for _, entry := range entries {
			combined.WriteString(entry + "\n")
		}
		combined.WriteString("\n")
	}

	content := combined.String()
	hash := fmt.Sprintf("%x", sha256.Sum256([]byte(content)))
	return TranslateResult{INI: content, SHA256: hash}
}

func appendUnique(slice []string, item string) []string {
	for _, s := range slice {
		if s == item {
			return slice
		}
	}
	return append(slice, item)
}
